parameters:
#    hflan_registration.example.class: hflan\RegistrationBundle\Example

services:
#    hflan_registration.example:
#        class: %hflan_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
