parameters:
#    hflan_tournament.example.class: hflan\TournamentBundle\Example

services:
#    hflan_tournament.example:
#        class: %hflan_tournament.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
